### ISSUE TITLE
Incorrect dependency example 1.0.0 in readme

### ISSUE THREAD

**Issue by escay** [Swagger2Markup/markup-document-builder#27]
The readme contains:

```
<dependency>
    <groupId>io.github.robwin</groupId>
    <artifactId>markup-document-builder</artifactId>
    <version>1.0.0</version>
</dependency>

```
this version does not exist in maven central. Perhaps it is useful to update the readme to:

        <dependency>
            <groupId>io.github.swagger2markup</groupId>
            <artifactId>markup-document-builder</artifactId>
            <version>1.1.1</version>
        </dependency>

Too bad the nl.jworks.markdown_to_asciidoc dependency is not in maven central.
https://github.com/Swagger2Markup/swagger2markup-maven-plugin/issues/25

**Comment by RobWin** [comment]
Thx. Fixed
