### ISSUE TITLE
Refactor anchor and cross-reference interface and implementation

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/markup-document-builder#9]
Context :
- Many limitations on supported characters in MD and ADOC anchors, and HTML generated ids.
- Different normalization rules when cross-referencing titles over custom anchors
- We should always cross-reference a stable id instead of a moving title
- Partial AsciiDoctor support for title cross-referencing (does not work with inter-document cross-references)

Solution :
- We decide to genericize the anchor/sections/cross-references system in markup-document-builder to a LCD character set for anchors (narrower than the AsciiDoc|Markdown specification).
- No more distinct crossReferenceTitle() : only crossReference and crossReferenceRaw (no filtering, you put what you want in anchor if you know what you do)
- Each section generated with the tool will have an explicit id with anchor = normalized(title)
- All anchors are normalized this way :

```
- current <- trim()
- input <- current
- current <- Normalizer.normalize(Normalizer.Form.NFD)
- current <- replaceAll("\\p{Punct}+", "")
- current <- lowercase()
- current <- replaceAll("\\s+", ADOC("_") | MD("-") )
- base <- current
- current <- replaceAll("[^a-z0-9-_]+", "")
if (current.size() != base.size())
  - current <- hash(input) // use input to maximize uniqueness
end

if (ADOC)
  - current <- prefix with "_"
  - current <- suffix with "_" if endsWith("-") 
end
```
## Notes

When a section has an explicit custom anchor, AsciiDoctor reuse it as-is for HTML id generation.
### Markdown

Sections :
- trim
- supports UTF-8
- only lower cases
- no spaces (replaced with - )
- supported punctuation : [-] ... to be continued

Manual anchors :
- <=> HTML ids
### AsciiDoc

Sections :
- no limitations

Manual anchors :
- trim
- support upper cases
- no UTF-8
- no space (replaced with _ )
- can't start with a digit
- can't end with '-' ( <<anchor->> : parse error)
- supported punctuation : [:-_.] ... to be continued
- ...
### HTML

HTML 4
ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters (UTF-8), digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

HTML 5 : 
The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters.
There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.
An element's unique identifier can be used for a variety of purposes, most notably as a way to link to specific parts of a document using fragment identifiers, as a way to target an element when scripting, and as a way to style a specific element from CSS.

**Comment by RobWin** [comment]
Thx for the documentation of the requirements.

**Comment by RobWin** [comment]
I just have 1 comment. See PR

**Comment by RobWin** [comment]
Nice. I didn't know that you can auto-close an issue with a Pull Request commit message :)
